name: CI App
on:
  push
jobs:

 build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

      
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64

    
    - name: Compile Gradle and sonar scanner
      run: |
        chmod +x gradlew
        ./gradlew build sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}


    - name: Docker build
      run: |
        docker build --tag toobal7/article_dec_28_mavengradle-based-multi-module-spring-boot-microservices:lastest .

    - name: Docker Push
      run: |
        docker push toobal7/article_dec_28_mavengradle-based-multi-module-spring-boot-microservices:lastest

 deploy:
   needs: build
   runs-on: self-hosted
   steps:

      - name: Checkout
        uses: actions/checkout@v3

     # - name: 
    
 
