name: CI App
on:
  push
jobs:

 build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

      
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64

    
    - name: Compile Gradle and sonar scanner
      run: |
        chmod +x gradlew
        ./gradlew build sonar -Dsonar.token=${{ secrets.SONAR_TOKEN }}

