name: CI App
on:
  [workflow_dispatch, push]
concurrency: ci-app-${{ github.ref }}
jobs:

 build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3
      

    
